make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e
make && make d && ./o | cat -e


